import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import {
  collection,
  query,
  where,
  onSnapshot,
  addDoc,
  deleteDoc,
  doc,
  setDoc,
  getDoc,

  type Unsubscribe,
} from 'firebase/firestore';
import { db } from '@/services/firebase';
import i18n from '@/i18n/config';
import {
  type Expense,
  type Income,
  type Budget,
  type UserSettings,
  type BudgetSummary,
  type SpendingBadge,
  DEFAULT_BUDGET,
  DEFAULT_CATEGORIES,
  SPENDING_BADGE_CONFIG,
} from '@/types/budget.types';

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Strips `undefined` values (Firestore rejects them). */
function removeUndefined<T extends Record<string, unknown>>(obj: T): Partial<T> {
  return Object.fromEntries(
    Object.entries(obj).filter(([, v]) => v !== undefined)
  ) as Partial<T>;
}

function getMonthKey(date = new Date()) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
}

function getWeekStart() {
  const d = new Date();
  const day = d.getDay(); // 0 = Sunday
  const diff = d.getDate() - day + (day === 0 ? -6 : 1); // Monday
  return new Date(d.setDate(diff));
}

function computeBadge(pct: number): SpendingBadge {
  if (pct >= 100) return 'fuori_budget';
  if (pct >= 90) return 'spendaccione';
  if (pct >= 80) return 'attenzione';
  if (pct >= 60) return 'buon_risparmiatore';
  return 'risparmiatore_master';
}

function computeSummary(expenses: Expense[], budget: Budget): BudgetSummary {
  const now = new Date();
  const monthKey = getMonthKey(now);
  const weekStart = getWeekStart();

  const fixedTemplates = expenses.filter(e => e.isFixed);
  const totalFixedTemplates = fixedTemplates.reduce((s, e) => s + e.amount, 0);

  // Variable expenses: not templates and not auto-generated copies (those are handled by templates weight)
  const variableExpenses = expenses.filter((e) => 
    e.date.startsWith(monthKey) && 
    !e.isFixed && 
    !e.isAutoGenerated
  );

  const totalVariableMonth = variableExpenses.reduce((s, e) => s + e.amount, 0);
  const totalMonth = totalVariableMonth + totalFixedTemplates;

  const weeklyExpenses = variableExpenses.filter((e) => new Date(e.date) >= weekStart);
  const totalWeek = weeklyExpenses.reduce((s, e) => s + e.amount, 0);

  const lastDay = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
  const daysLeft = lastDay - now.getDate();

  const monthPct = budget.monthlyLimit > 0 ? (totalMonth / budget.monthlyLimit) * 100 : 0;
  const weekPct = budget.weeklyLimit > 0 ? (totalWeek / budget.weeklyLimit) * 100 : 0;

  return {
    totalSpentThisMonth: totalMonth,
    totalVariableThisMonth: totalVariableMonth,
    totalFixedThisMonth: totalFixedTemplates,
    totalSpentThisWeek: totalWeek,
    monthlyRemaining: Math.max(budget.monthlyLimit - totalMonth, 0),
    weeklyRemaining: Math.max(budget.weeklyLimit - totalWeek, 0),
    monthlyPercentage: Math.min(monthPct, 100),
    weeklyPercentage: Math.min(weekPct, 100),
    daysLeftInMonth: daysLeft,
    spendingBadge: computeBadge(monthPct),
  };
}

// ─── Store types ──────────────────────────────────────────────────────────────
interface BudgetState {
  expenses: Expense[];
  incomes: Income[];
  budget: Budget;
  settings: UserSettings | null;
  privacyMode: boolean;
  summary: BudgetSummary | null;
  isLoading: boolean;
  _unsubExpenses: Unsubscribe | null;
  _unsubIncomes: Unsubscribe | null;
  _unsubFamilyBudget: Unsubscribe | null;

  // Actions
  subscribeToExpenses: (userId: string) => void;
  unsubscribeExpenses: () => void;
  addIncome: (income: Omit<Income, 'id'>) => Promise<string>;
  updateIncome: (id: string, partial: Partial<Income>) => Promise<void>;
  deleteIncome: (id: string) => Promise<void>;
  addExpense: (expense: Omit<Expense, 'id'>) => Promise<string>;
  deleteExpense: (expenseId: string) => Promise<void>;
  updateExpense: (expenseId: string, partial: Partial<Expense>) => Promise<void>;
  updateBudget: (budget: Budget) => void;
  updateFamilyBudget: (userId: string, budget: Budget) => Promise<void>;
  loadSettings: (userId: string) => Promise<void>;
  saveSettings: (userId: string, settings: Partial<UserSettings>) => Promise<void>;
  togglePrivacyMode: () => void;
  runFixedExpensesForMonth: (userId: string) => Promise<void>;
  removeFamilyMember: (memberId: string) => Promise<void>;
  resetBudgetStore: () => void;
}

// ─── Store ────────────────────────────────────────────────────────────────────
export const useBudgetStore = create<BudgetState>()(
  persist(
    (set, get) => ({
      expenses: [],
      incomes: [],
      budget: DEFAULT_BUDGET,
      settings: null,
      privacyMode: false,
      summary: null,
      isLoading: false,
      _unsubExpenses: null,
      _unsubIncomes: null,
      _unsubFamilyBudget: null,

      subscribeToExpenses: (userId: string) => {
        // Unsubscribe from any existing listener
        get()._unsubExpenses?.();
        get()._unsubFamilyBudget?.();

        const queryId = get().settings?.familyId || userId;
        const qExp = query(
          collection(db, 'expenses'),
          where('familyId', '==', queryId)
        );

        const unsubExp = onSnapshot(qExp, (snapshot) => {
          const expenses: Expense[] = snapshot.docs.map((d) => ({
            id: d.id,
            ...(d.data() as Omit<Expense, 'id'>),
          }));
          const summary = computeSummary(expenses, get().budget);
          set({ expenses, summary });
        });

        const qInc = query(
          collection(db, 'incomes'),
          where('familyId', '==', queryId)
        );

        const unsubInc = onSnapshot(qInc, (snapshot) => {
          const incomes: Income[] = snapshot.docs.map((d) => ({
            id: d.id,
            ...(d.data() as Omit<Income, 'id'>),
          }));
          set({ incomes });
        });

        // Subscribe to shared family budget (same for all family members)
        const familyId = get().settings?.familyId;
        let unsubFamilyBudget: Unsubscribe | null = null;
        if (familyId) {
          unsubFamilyBudget = onSnapshot(doc(db, 'familyBudget', familyId), (snap) => {
            if (snap.exists()) {
              const familyBudget = snap.data() as Budget;
              const summary = computeSummary(get().expenses, familyBudget);
              set((s) => ({
                budget: familyBudget,
                summary,
                settings: s.settings ? { ...s.settings, familyBudget } : s.settings,
              }));
            }
          });
        }

        set({ _unsubExpenses: unsubExp, _unsubIncomes: unsubInc, _unsubFamilyBudget: unsubFamilyBudget });
      },

      unsubscribeExpenses: () => {
        get()._unsubExpenses?.();
        get()._unsubIncomes?.();
        get()._unsubFamilyBudget?.();
        set({ _unsubExpenses: null, _unsubIncomes: null, _unsubFamilyBudget: null });
      },

      addExpense: async (expense) => {
        const familyId = get().settings?.familyId || expense.userId;
        const docRef = await addDoc(
          collection(db, 'expenses'),
          removeUndefined({ ...expense, familyId, createdAt: Date.now() })
        );
        return docRef.id;
      },

      deleteExpense: async (expenseId) => {
        await deleteDoc(doc(db, 'expenses', expenseId));
      },

      updateExpense: async (expenseId, partial) => {
        await setDoc(doc(db, 'expenses', expenseId), partial, { merge: true });
      },

      addIncome: async (income) => {
        const familyId = get().settings?.familyId || income.userId;
        const docRef = await addDoc(
          collection(db, 'incomes'),
          removeUndefined({ ...income, familyId, createdAt: Date.now() })
        );
        return docRef.id;
      },

      updateIncome: async (id, partial) => {
        await setDoc(doc(db, 'incomes', id), partial, { merge: true });
      },

      deleteIncome: async (id) => {
        await deleteDoc(doc(db, 'incomes', id));
      },

      updateBudget: (budget) => {
        const summary = computeSummary(get().expenses, budget);
        set({ budget, summary });
      },

      updateFamilyBudget: async (userId, budget) => {
        const familyId = get().settings?.familyId || userId;
        // Write to shared familyBudget collection so all family members get it
        await setDoc(doc(db, 'familyBudget', familyId), budget, { merge: true });
        // Also update personal settings budget as fallback
        await setDoc(
          doc(db, 'userSettings', userId),
          { budget },
          { merge: true }
        );
        const summary = computeSummary(get().expenses, budget);
        set((s) => ({
          budget,
          summary,
          settings: s.settings ? { ...s.settings, budget, familyBudget: budget } : s.settings,
        }));
      },

      loadSettings: async (userId: string) => {
        set({ isLoading: true });
        const snap = await getDoc(doc(db, 'userSettings', userId));
        if (snap.exists()) {
          const settings = snap.data() as UserSettings;
          // Check if there is a shared family budget
          let activeBudget = settings.budget ?? DEFAULT_BUDGET;
          if (settings.familyId) {
            const familySnap = await getDoc(doc(db, 'familyBudget', settings.familyId));
            if (familySnap.exists()) {
              activeBudget = familySnap.data() as Budget;
            }
          }
          set({
            settings: { ...settings, familyBudget: activeBudget },
            budget: activeBudget,
            privacyMode: settings.privacyMode ?? false,
            isLoading: false,
          });
        } else {
          // Create defaults
          const defaultSettings: UserSettings = {
            userId,
            budget: DEFAULT_BUDGET,
            privacyMode: false,
            currency: '€',
          };
          await setDoc(doc(db, 'userSettings', userId), defaultSettings);
          set({
            settings: defaultSettings,
            budget: DEFAULT_BUDGET,
            isLoading: false,
          });
        }
      },

      saveSettings: async (userId, partial) => {
        const current = get().settings;
        const updated: UserSettings = {
          userId,
          budget: DEFAULT_BUDGET,
          privacyMode: false,
          currency: '€',
          ...current,
          ...partial,
        };
        await setDoc(doc(db, 'userSettings', userId), updated, { merge: true });
        set({ settings: updated });
        if (partial.budget) {
          const summary = computeSummary(get().expenses, partial.budget);
          set({ budget: partial.budget, summary });
        }
      },

      togglePrivacyMode: () => {
        set((s) => ({ privacyMode: !s.privacyMode }));
      },

      /**
       * Called once per month (on first login of the month).
       * Auto-adds all fixed expenses to the current month.
       */
      runFixedExpensesForMonth: async (userId: string) => {
        const monthKey = getMonthKey();
        const { settings, expenses } = get();

        // Prevent double-run
        if (settings?.lastFixedExpensesRun === monthKey) return;

        const fixedExpenses = expenses.filter((e) => e.isFixed);
        if (fixedExpenses.length === 0) return;

        const now = new Date();
        const year = now.getFullYear();
        const month = String(now.getMonth() + 1).padStart(2, '0');
        const today = now.toISOString().split('T')[0];

        const batch = fixedExpenses.map((fe) => {
          const expenseDate = fe.billingDay 
            ? `${year}-${month}-${String(fe.billingDay).padStart(2, '0')}` 
            : today;
            
          let currentInst = fe.currentInstallment;
          let nextInst = currentInst !== undefined ? currentInst + 1 : undefined;

          // If it's a financing, update the template to increment currentInstallment
          if (fe.isFinancing && fe.id && nextInst !== undefined) {
            setDoc(doc(db, 'expenses', fe.id), { currentInstallment: nextInst }, { merge: true }).catch(console.error);
          }

          return addDoc(
            collection(db, 'expenses'),
            removeUndefined({
              userId,
              amount: fe.amount,
              category: fe.category,
              date: expenseDate,
              description: `[${i18n.t('spendless.auto_prefix')}] ${fe.description}`,
              isFixed: false,
              isAutoGenerated: true,
              accountSource: fe.accountSource ?? null,
              isFinancing: fe.isFinancing ?? false,
              totalFinanced: fe.totalFinanced ?? null,
              totalInstallments: fe.totalInstallments ?? null,
              currentInstallment: currentInst ?? null,
              createdAt: Date.now(),
              familyId: get().settings?.familyId || userId,
            })
          );
        });

        await Promise.all(batch);

        // Mark as run for this month
        await setDoc(
          doc(db, 'userSettings', userId),
          { lastFixedExpensesRun: monthKey },
          { merge: true }
        );
        set((s) => ({
          settings: s.settings ? { ...s.settings, lastFixedExpensesRun: monthKey } : s.settings,
        }));
      },

      removeFamilyMember: async (memberId: string) => {
        await setDoc(doc(db, 'userSettings', memberId), { familyId: null, familyBudget: null }, { merge: true });
      },

      resetBudgetStore: () => {
        get()._unsubExpenses?.();
        get()._unsubFamilyBudget?.();
        set({
          expenses: [],
          budget: DEFAULT_BUDGET,
          settings: null,
          privacyMode: false,
          summary: null,
          isLoading: false,
          _unsubExpenses: null,
          _unsubFamilyBudget: null,
        });
      },
    }),
    {
      name: 'budget-storage',
      partialize: (state) => ({
        budget: state.budget,
        privacyMode: state.privacyMode,
      }),
    }
  )
);

// Re-export for convenience
export { computeSummary, getMonthKey, SPENDING_BADGE_CONFIG, DEFAULT_CATEGORIES };
