// ─── Expense ─────────────────────────────────────────────────────────────────
export type ExpenseCategory =
  | 'alimentari'
  | 'trasporti'
  | 'casa'
  | 'salute'
  | 'intrattenimento'
  | 'abbigliamento'
  | 'ristoranti'
  | 'tecnologia'
  | 'istruzione'
  | 'altro';

export interface Expense {
  id: string;
  userId: string;
  familyId?: string; // Used for querying shared expenses
  amount: number;
  category: ExpenseCategory;
  date: string; // ISO date string YYYY-MM-DD
  startDate?: string; // ISO date string YYYY-MM-DD for fixed expenses
  description: string;
  isFixed: boolean;
  receiptUrl?: string;
  createdAt: number; // timestamp
  billingDay?: number; // 1-31
  accountSource?: string; // e.g. Conto Corrente, Carta, etc.
  addedBy?: string; // name or email of user who added
  isAutoGenerated?: boolean; // to distinguish auto-added fixed expenses
  isFinancing?: boolean;
  totalFinanced?: number;
  totalInstallments?: number;
  currentInstallment?: number;
  location?: {
    lat: number;
    lng: number;
    label?: string;
  } | null;
}

export interface Income {
  id: string;
  userId: string;
  familyId?: string;
  amount: number;
  description: string;
  date: string;
  addedBy: string;
  createdAt: number;
  isExtra?: boolean;
  isFixed?: boolean;
}

// ─── Category Config ──────────────────────────────────────────────────────────
export interface CategoryConfig {
  name: ExpenseCategory;
  limit: number;
  icon: string;
  color: string;
}

// ─── Budget ───────────────────────────────────────────────────────────────────
export interface Budget {
  monthlyLimit: number;
  weeklyLimit: number;
  categoriesConfig: CategoryConfig[];
}

// ─── User Settings (stored in Firestore userSettings collection) ──────────────
export interface UserSettings {
  userId: string;
  familyId?: string; // Used to share budget with other users
  budget: Budget;
  privacyMode: boolean;
  currency: string;
  lastFixedExpensesRun?: string; // YYYY-MM month key
  familyBudget?: Budget; // Shared budget for the family (overrides personal budget for family members)
}

// ─── Computed budget state ────────────────────────────────────────────────────
export interface BudgetSummary {
  totalSpentThisMonth: number;
  totalVariableThisMonth: number; // variable only (no fixed templates)
  totalFixedThisMonth: number; // fixed only (totalFixedTemplates)
  totalSpentThisWeek: number;
  monthlyRemaining: number;
  weeklyRemaining: number;
  monthlyPercentage: number;
  weeklyPercentage: number;
  daysLeftInMonth: number;
  spendingBadge: SpendingBadge;
}

export type SpendingBadge =
  | 'risparmiatore_master'
  | 'buon_risparmiatore'
  | 'attenzione'
  | 'spendaccione'
  | 'fuori_budget';

export const SPENDING_BADGE_CONFIG: Record<
  SpendingBadge,
  { label: string; emoji: string; color: string; threshold: number }
> = {
  risparmiatore_master: {
    label: 'Risparmiatore Master',
    emoji: '🏆',
    color: 'from-emerald-400 to-emerald-600',
    threshold: 0,
  },
  buon_risparmiatore: {
    label: 'Buon Risparmiatore',
    emoji: '✅',
    color: 'from-teal-400 to-teal-600',
    threshold: 60,
  },
  attenzione: {
    label: 'Occhio alle Spese',
    emoji: '⚠️',
    color: 'from-amber-400 to-amber-600',
    threshold: 80,
  },
  spendaccione: {
    label: 'Spendaccione',
    emoji: '🔥',
    color: 'from-orange-400 to-orange-600',
    threshold: 90,
  },
  fuori_budget: {
    label: 'Fuori Budget!',
    emoji: '💸',
    color: 'from-red-500 to-rose-600',
    threshold: 100,
  },
};

// ─── Default values ───────────────────────────────────────────────────────────
export const DEFAULT_CATEGORIES: CategoryConfig[] = [
  { name: 'alimentari', limit: 400, icon: '🛒', color: '#10b981' },
  { name: 'trasporti', limit: 150, icon: '🚗', color: '#3b82f6' },
  { name: 'casa', limit: 800, icon: '🏠', color: '#8b5cf6' },
  { name: 'salute', limit: 100, icon: '💊', color: '#f43f5e' },
  { name: 'intrattenimento', limit: 100, icon: '🎬', color: '#f59e0b' },
  { name: 'abbigliamento', limit: 150, icon: '👕', color: '#ec4899' },
  { name: 'ristoranti', limit: 200, icon: '🍕', color: '#ef4444' },
  { name: 'tecnologia', limit: 80, icon: '💻', color: '#06b6d4' },
  { name: 'istruzione', limit: 100, icon: '📚', color: '#6366f1' },
  { name: 'altro', limit: 200, icon: '📦', color: '#78716c' },
];

export const DEFAULT_BUDGET: Budget = {
  monthlyLimit: 2000,
  weeklyLimit: 500,
  categoriesConfig: DEFAULT_CATEGORIES,
};
